/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multithread;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JProgressBar;
import javax.swing.Timer;
public class anaSunucu extends javax.swing.JFrame {
    public static int kapasite;
    public static long start = System.currentTimeMillis();
    public static int altSunucu[] = new int[100];
    public static Thread sunucular[] = new Thread[100];
    public static boolean flags[] = new boolean[100];
    public static int calisan = 0;
    public static int sunucu = 0;
    public int progress_kapasite=0;
    public int alt_kapasite_0_deger=0;
    public int alt_kapasite_1_deger=0;
    public int alt_kapasite_2_deger=0;
    public int alt_kapasite_3_deger=0;
    public int alt_kapasite_4_deger=0;
    public int alt_kapasite_5_deger=0;
    public int alt_kapasite_6_deger=0;
    public int alt_kapasite_7_deger=0;
    public int alt_kapasite_8_deger=0;
    public int alt_kapasite_9_deger=0; 
    public int alt_kapasite_10_deger=0; 
    public int alt_kapasite_11_deger=0;
   
    altSunucu alt_sunucu=new altSunucu();
    baslatici basla=new baslatici();
    JProgressBar p,p1,p2,p3,p4,p5,p6,p7,p8,p9;
    public anaSunucu(int kapasite) {
        anaSunucu.kapasite = kapasite;
    }
    public anaSunucu() {
        initComponents();

    }
    public void run() {
        new anaSunucu().setVisible(true);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        ana_progress = new javax.swing.JProgressBar();
        baslat_buton = new javax.swing.JButton();
        ana_label = new javax.swing.JLabel();
        alt_progress_0 = new javax.swing.JProgressBar();
        alt_progress_1 = new javax.swing.JProgressBar();
        alt_label_1 = new javax.swing.JLabel();
        alt_label_0 = new javax.swing.JLabel();
        alt_label_3 = new javax.swing.JLabel();
        alt_label_2 = new javax.swing.JLabel();
        alt_label_4 = new javax.swing.JLabel();
        alt_label_5 = new javax.swing.JLabel();
        alt_label_6 = new javax.swing.JLabel();
        alt_label_7 = new javax.swing.JLabel();
        alt_label_8 = new javax.swing.JLabel();
        alt_label_9 = new javax.swing.JLabel();
        alt_label_10 = new javax.swing.JLabel();
        alt_label_11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ana_progress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ana_progress.setName(""); // NOI18N
        ana_progress.setRequestFocusEnabled(false);
        ana_progress.setStringPainted(true);
        ana_progress.setVerifyInputWhenFocusTarget(false);

        baslat_buton.setText("başlat");
        baslat_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslat_butonActionPerformed(evt);
            }
        });

        ana_label.setText("ana sunucu kapasite:");

        alt_progress_0.setStringPainted(true);

        alt_progress_1.setStringPainted(true);

        alt_label_1.setText("alt sunucu kapasite:");

        alt_label_0.setText("alt sunucu kapasite:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(alt_label_0)
                        .addGap(160, 160, 160)
                        .addComponent(alt_label_1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(ana_label, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(ana_progress, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(baslat_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alt_progress_0, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt_label_2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt_label_4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt_label_6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt_label_8, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt_label_10, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alt_progress_1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(alt_label_9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alt_label_7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alt_label_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alt_label_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(alt_label_11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(baslat_buton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ana_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ana_progress, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt_label_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt_label_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alt_progress_0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt_progress_1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt_label_3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt_label_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(alt_label_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt_label_5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(alt_label_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt_label_7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(alt_label_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt_label_9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt_label_10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt_label_11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        alt_progress_0.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baslat_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslat_butonActionPerformed
         Timer timer = new Timer(500,null);
        timer.addActionListener(new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 progress_kapasite=anaSunucu.kapasite/100;
                 ana_progress.setValue(progress_kapasite);
                 ana_label.setText("Ana sunucu kapasite:" +anaSunucu.kapasite);
                 
                 alt_kapasite_0_deger=multithread.altSunucu.alt_thread_kapasite_0/50;
                 alt_progress_0.setValue(alt_kapasite_0_deger);
                 alt_label_0.setText("Alt sunucu kapasite:"+multithread.altSunucu.alt_thread_kapasite_0);
                 
                 alt_kapasite_1_deger=multithread.altSunucu.alt_thread_kapasite_1/50;
                 alt_progress_1.setValue(alt_kapasite_1_deger);
                 alt_label_1.setText("Alt sunucu kapasite:"+multithread.altSunucu.alt_thread_kapasite_1);

                for(int i = 0; i <= anaSunucu.sunucu; i++){
                    if(i==2 && altSunucu[i] != 0) alt_label_2.setText("3.alt sunucu kapasite:"+altSunucu[i]);
                    if(i==3 && altSunucu[i] != 0) alt_label_3.setText("4.alt sunucu kapasite:"+altSunucu[i]);
                    if(i==4 && altSunucu[i] != 0) alt_label_4.setText("5.alt sunucu kapasite:"+altSunucu[i]);
                    if(i==5 && altSunucu[i] != 0) alt_label_5.setText("6.alt sunucu kapasite:"+altSunucu[i]);
                    if(i==6 && altSunucu[i] != 0) alt_label_6.setText("7.alt sunucu kapasite:"+altSunucu[i]);
                    if(i==7 && altSunucu[i] != 0) alt_label_7.setText("8.alt sunucu kapasite:"+altSunucu[i]);
                    if(i==8 && altSunucu[i] != 0) alt_label_8.setText("9.alt sunucu kapasite:"+altSunucu[i]);
                    if(i==9 && altSunucu[i] != 0) alt_label_9.setText("10.alt sunucu kapasite:"+altSunucu[i]);
                    if(i==10 && altSunucu[i] != 0) alt_label_10.setText("11.alt sunucu kapasite:"+altSunucu[i]);
                    if(i==11 && altSunucu[i] != 0) alt_label_11.setText("12.alt sunucu kapasite:"+altSunucu[i]);
                }
                for(int i = 0; i <= anaSunucu.sunucu; i++){
                    if(i==2 && altSunucu[i] == 0) alt_label_2.setText("3.alt sunucu kapalı");
                    if(i==3 && altSunucu[i] == 0) alt_label_3.setText("4.alt sunucu kapalı");
                    if(i==4 && altSunucu[i] == 0) alt_label_4.setText("5.alt sunucu kapalı");
                    if(i==5 && altSunucu[i] == 0) alt_label_5.setText("6.alt sunucu kapalı");
                    if(i==6 && altSunucu[i] == 0) alt_label_6.setText("7.alt sunucu kapalı");
                    if(i==7 && altSunucu[i] == 0) alt_label_7.setText("8.alt sunucu kapalı");
                    if(i==8 && altSunucu[i] == 0) alt_label_8.setText("9.alt sunucu kapalı");
                    if(i==9 && altSunucu[i] == 0) alt_label_9.setText("10.alt sunucu kapalı");
                    if(i==10 && altSunucu[i] == 0) alt_label_10.setText("11.alt sunucu kapalı");
                    if(i==11 && altSunucu[i] == 0) alt_label_11.setText("12.alt sunucu kapalı");
                }
             }
         });
       timer.start();
    
    }//GEN-LAST:event_baslat_butonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alt_label_0;
    private javax.swing.JLabel alt_label_1;
    private javax.swing.JLabel alt_label_10;
    private javax.swing.JLabel alt_label_11;
    private javax.swing.JLabel alt_label_2;
    private javax.swing.JLabel alt_label_3;
    private javax.swing.JLabel alt_label_4;
    private javax.swing.JLabel alt_label_5;
    private javax.swing.JLabel alt_label_6;
    private javax.swing.JLabel alt_label_7;
    private javax.swing.JLabel alt_label_8;
    private javax.swing.JLabel alt_label_9;
    private javax.swing.JProgressBar alt_progress_0;
    private javax.swing.JProgressBar alt_progress_1;
    private javax.swing.JLabel ana_label;
    private javax.swing.JProgressBar ana_progress;
    private javax.swing.JButton baslat_buton;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables

  
}
